name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update package lists
        run: sudo apt-get update

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com | sh

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Run Docker Compose
        run: |
          pwd
          docker-compose -f $(pwd)/docker-compose.yml up -d

      - name: Check for and fix broken packages
        run: sudo apt-get install -f